name: my_custom_widget
description: "Mozaic Loyalty Sdk."
publish_to: 'none'
homepage:

version: 1.0.0+1

environment:
  sdk: ^3.9.0
  flutter: ">=1.17.0"

dependencies:
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  get: ^4.7.2
  get_it: ^8.2.0
  qr_flutter: ^4.1.0
  carousel_slider: ^5.1.1
  package_info_plus: ^8.0.0
  dartz: ^0.10.1
  internet_connection_checker: ^1.0.0+1
  flutter_svg: ^2.2.1
  http: ^1.5.0
  device_info_plus: ^12.2.0
  pin_code_fields: ^8.0.1
  intl: ^0.20.2
  cached_network_image: ^3.4.1
  lottie: ^3.3.2
  geolocator: ^14.0.2
  fluttertoast: ^9.0.0
  http_proxy_override: ^1.0.1
  flutter_screenutil: ^5.9.3
  permission_handler: ^12.0.1
  loading_animation_widget: ^1.3.0
  shared_preferences: ^2.5.3
  linkwell: ^2.0.6
  geocoding: ^4.0.0
  percent_indicator: ^4.2.5
  flutter_localization: ^0.3.3


dependency_overrides:
  package_info_plus: ^8.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  flutter_lints: ^6.0.0
  build_runner: ^2.10.0

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/svgs/
    - assets/images/
    - assets/gif/

  fonts:
    - family: font
      fonts:
        - asset: assets/fonts/font.ttf
        - asset: assets/fonts/font_bold.ttf